# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_epos'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='brief_content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
