# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_brief_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_year',
            field=models.PositiveIntegerField(max_length=4),
        ),
    ]
