# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_formatsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='format_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.FormatSize'),
        ),
    ]
